use_default_settings:
  engines:
    remove:
      - ahmia
      - startpage
      - torch
      - wikidata

server:
  secret_key: "astesia-internal-search-only"
  limiter: false
  image_proxy: false

search:
  safe_search: 1
  formats:
    - html
    - json
