import { StyleSheet } from 'react-native';
import {
  PRODUCTIVITY_PALETTE,
  type ProductivityPalette,
} from '@/constants/productivity-theme';

export function createAccountingStyles(AppPalette: ProductivityPalette) {
  return StyleSheet.create({
  // [变更] 修改前: 记账与资产页样式固定引用深色 AppPalette
  // [变更] 修改后: 使用传入的生产力页面色板动态生成卡片、文字和浮层颜色
  // [原因] 浅色模式下记账主页、资产页和弹层必须一起切换，不能只改外层背景
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  screen: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  assetGradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 120,
    gap: 14,
  },
  assetScrollContent: {
    paddingTop: 12,
    paddingBottom: 132,
    gap: 18,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  assetPage: {
    gap: 18,
  },
  assetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  assetHeaderTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetHeaderSpacer: {
    width: 36,
    height: 36,
  },
  assetOverviewCard: {
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceElevated,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  // [变更] 修改前: 资产和账单卡片内主信息块大量使用 row 横向分栏
  // [变更] 修改后: 主信息块改为 column 纵向堆叠
  // [原因] 当前记账页要求页面内容按纵向排列
  assetOverviewHeader: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 16,
  },
  assetOverviewTextGroup: {
    width: '100%',
  },
  assetOverviewTitle: {
    fontSize: 26,
    lineHeight: 34,
    fontWeight: '600',
    color: AppPalette.text,
  },
  assetOverviewAmount: {
    marginTop: 10,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetOverviewActionGroup: {
    alignItems: 'stretch',
    gap: 8,
  },
  assetOverviewActionButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: AppPalette.brandSoft,
  },
  assetOverviewActionText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: AppPalette.brandLight,
  },
  assetBillLinkRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 12,
    marginTop: 30,
  },
  assetBillLinkButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetBillLinkText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: AppPalette.text,
  },
  assetOverviewDivider: {
    height: StyleSheet.hairlineWidth,
    marginTop: 18,
    marginBottom: 16,
    backgroundColor: AppPalette.border,
  },
  assetBalanceRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 6,
  },
  assetBalanceLabel: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: AppPalette.text,
  },
  assetBalanceValue: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '700',
  },
  assetBalancePositive: {
    color: AppPalette.text,
  },
  assetBalanceNegative: {
    color: '#DC2626',
  },
  assetMetricCard: {
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 18,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceElevated,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  assetMetricHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 6,
    marginBottom: 18,
  },
  assetMetricHeaderLabel: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '600',
    color: AppPalette.text,
  },
  assetMetricHeaderValue: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
  },
  assetMetricGrid: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 12,
  },
  assetMetricStat: {
    width: '100%',
    alignItems: 'center',
    borderRadius: 24,
    paddingHorizontal: 10,
    paddingVertical: 18,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetMetricStatLabel: {
    fontSize: 15,
    lineHeight: 20,
    color: AppPalette.textMuted,
    textAlign: 'center',
  },
  assetMetricStatValue: {
    marginTop: 16,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetMetricStatUnit: {
    marginTop: 10,
    fontSize: 16,
    lineHeight: 22,
    color: AppPalette.textMuted,
  },
  assetSearchCard: {
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 26,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceElevated,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  assetSearchTitle: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
    color: AppPalette.text,
  },
  assetSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 18,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetSearchInput: {
    flex: 1,
    paddingVertical: 0,
    fontSize: 16,
    lineHeight: 22,
    color: AppPalette.text,
  },
  assetSearchPlaceholder: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    color: AppPalette.textMuted,
  },
  assetRangeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  assetRangeChip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: AppPalette.brandSoft,
  },
  assetRangeChipActive: {
    backgroundColor: AppPalette.brand,
  },
  assetRangeChipText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: AppPalette.brandLight,
  },
  assetRangeChipTextActive: {
    color: '#FFFFFF',
  },
  assetTrendPanel: {
    marginTop: 20,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 14,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetTrendHeader: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 10,
  },
  assetTrendName: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetTrendCode: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: AppPalette.textMuted,
  },
  assetTrendPriceGroup: {
    alignItems: 'flex-start',
  },
  assetTrendPrice: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetTrendRate: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  assetTrendChart: {
    marginTop: 18,
    height: 132,
    overflow: 'hidden',
  },
  assetTrendFooter: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    marginTop: 8,
  },
  assetTrendFooterText: {
    fontSize: 12,
    lineHeight: 16,
    color: AppPalette.textMuted,
  },
  assetCandleDetailCard: {
    marginTop: 12,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: AppPalette.surface,
  },
  assetCandleDetailHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    marginBottom: 8,
  },
  assetCandleDetailTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetCandleDetailRate: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  assetCandleDetailGrid: {
    flexDirection: 'column',
    gap: 6,
  },
  assetCandleDetailText: {
    width: '100%',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: AppPalette.textMuted,
  },
  assetTrendEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 24,
    backgroundColor: AppPalette.surfaceSoft,
    gap: 8,
  },
  assetTrendEmptyText: {
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
    textAlign: 'center',
  },
  assetSearchModalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    backgroundColor: AppPalette.overlay,
  },
  assetSearchModalCard: {
    width: '100%',
    height: '60%',
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 16,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceElevated,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 14,
  },
  assetSearchModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  assetSearchModalTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '800',
    color: AppPalette.text,
  },
  assetSearchModalClose: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetSearchModalInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetSearchResultList: {
    paddingTop: 14,
    paddingBottom: 8,
    gap: 10,
  },
  assetSearchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetSearchResultName: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetSearchResultMeta: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: AppPalette.textMuted,
  },
  assetSearchResultPrice: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: AppPalette.text,
  },
  assetSearchEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 42,
    gap: 8,
  },
  assetSearchEmptyText: {
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  monthText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: AppPalette.text,
  },
  heroCard: {
    height: 192,
    borderRadius: 18,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceSoft,
  },
  heroContent: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  heroTopRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 10,
  },
  heroLabel: {
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '800',
    color: AppPalette.text,
  },
  heroBalance: {
    marginTop: 4,
    fontSize: 18,
    lineHeight: 28,
    color: AppPalette.text,
  },
  heroSummary: {
    marginTop: 4,
    fontSize: 18,
    lineHeight: 28,
    color: AppPalette.textMuted,
  },
  heroSummaryRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
  },
  heroSummaryLink: {
    paddingVertical: 4,
  },
  card: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceSoft,
  },
  cardHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: AppPalette.text,
  },
  cardSubtitle: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
  },
  assetMetricRow: {
    flexDirection: 'column',
    gap: 12,
  },
  assetMetricItem: {
    width: '100%',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 14,
    backgroundColor: AppPalette.surfaceSoft,
  },
  assetMetricValue: {
    marginTop: 8,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: AppPalette.text,
  },
  budgetEditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: AppPalette.brandSoft,
  },
  budgetEditText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: AppPalette.brandLight,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E7F6EF',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#24C17E',
  },
  budgetSummaryRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: 14,
    gap: 8,
  },
  budgetInfoGroup: {
    width: '100%',
    gap: 4,
  },
  budgetDailyLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  budgetHelpButton: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: AppPalette.brandSoft,
  },
  budgetHelpText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: AppPalette.brandLight,
  },
  mutedText: {
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
  },
  chart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    minHeight: 210,
    marginTop: 10,
    paddingHorizontal: 4,
  },
  chartColumn: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  chartValue: {
    fontSize: 12,
    lineHeight: 16,
    color: '#F28B8E',
  },
  chartBarSlot: {
    height: 128,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  chartBar: {
    width: 11,
    borderRadius: 999,
    backgroundColor: '#F05A5A',
  },
  chartBarPlaceholder: {
    width: 11,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'transparent',
  },
  chartLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: AppPalette.textMuted,
  },
  billCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceSoft,
    overflow: 'hidden',
  },
  billHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: AppPalette.surfaceElevated,
  },
  billDate: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: AppPalette.text,
  },
  billTotal: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: AppPalette.text,
  },
  billItem: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: 'transparent',
  },
  billItemPressed: {
    backgroundColor: AppPalette.surfaceSoft,
  },
  billItemBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: AppPalette.border,
  },
  billItemLeft: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  billItemTextGroup: {
    flex: 1,
    gap: 2,
  },
  billDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F05A5A',
  },
  billDotIncome: {
    backgroundColor: '#24C17E',
  },
  billItemTitle: {
    fontSize: 16,
    lineHeight: 22,
    color: AppPalette.text,
  },
  billItemMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: AppPalette.textMuted,
  },
  billItemAmount: {
    alignSelf: 'flex-start',
    fontSize: 15,
    lineHeight: 20,
    color: '#F05A5A',
  },
  billItemAmountIncome: {
    color: '#24C17E',
  },
  emptyBillCard: {
    alignItems: 'center',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 28,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceSoft,
    gap: 8,
  },
  emptyBillTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: AppPalette.text,
  },
  emptyBillText: {
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
    textAlign: 'center',
  },
  bottomBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 28,
    paddingHorizontal: 28,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.toolbarBackground,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
  },
  bottomTab: {
    width: 56,
    alignItems: 'center',
    gap: 4,
  },
  bottomTabLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: AppPalette.textSubtle,
  },
  bottomTabLabelActive: {
    color: AppPalette.brandLight,
  },
  addButton: {
    width: 56,
    height: 56,
    marginTop: -24,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppPalette.brand,
    shadowColor: AppPalette.brandLight,
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  actionModalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: AppPalette.overlay,
  },
  actionSheetCard: {
    width: '80%',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 14,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceElevated,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  actionSheetTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '800',
    color: AppPalette.text,
  },
  actionSheetDescription: {
    marginTop: 6,
    marginBottom: 16,
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
  },
  actionSheetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: AppPalette.surfaceSoft,
  },
  actionSheetButtonSpaced: {
    marginTop: 10,
  },
  actionSheetButtonText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: AppPalette.brandLight,
  },
  actionSheetDeleteText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#DC2626',
  },
  actionSheetCancelButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    borderRadius: 18,
    paddingVertical: 13,
    backgroundColor: AppPalette.surfaceSoft,
  },
  actionSheetCancelText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: AppPalette.textMuted,
  },
  confirmDialogCard: {
    width: '100%',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceElevated,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  confirmDialogTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '800',
    color: AppPalette.text,
  },
  confirmDialogDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
  },
  confirmDialogActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 20,
  },
  confirmDialogCancelButton: {
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundColor: AppPalette.surfaceSoft,
  },
  confirmDialogCancelText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: AppPalette.textMuted,
  },
  confirmDialogDeleteButton: {
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#EF4444',
  },
  confirmDialogDeleteText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  modalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: AppPalette.overlay,
  },
  modalCard: {
    width: '100%',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: AppPalette.border,
    backgroundColor: AppPalette.surfaceElevated,
    shadowColor: AppPalette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  modalTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '800',
    color: AppPalette.text,
  },
  modalDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: AppPalette.textMuted,
  },
  pickerScopeRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  pickerScopeButton: {
    flex: 1,
    alignItems: 'center',
    borderRadius: 14,
    paddingVertical: 11,
    backgroundColor: AppPalette.surfaceSoft,
  },
  pickerScopeButtonActive: {
    backgroundColor: AppPalette.brandSoft,
  },
  pickerScopeText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: AppPalette.textMuted,
  },
  pickerScopeTextActive: {
    color: AppPalette.brandLight,
  },
  pickerSectionTitle: {
    marginTop: 18,
    marginBottom: 10,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
    color: AppPalette.text,
  },
  pickerChipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pickerChip: {
    minWidth: 72,
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: AppPalette.surfaceSoft,
  },
  pickerChipActive: {
    backgroundColor: AppPalette.brand,
  },
  pickerChipText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
    color: AppPalette.textMuted,
  },
  pickerChipTextActive: {
    color: '#FFFFFF',
  },
  budgetInput: {
    marginTop: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: AppPalette.borderStrong,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    lineHeight: 22,
    color: AppPalette.text,
    backgroundColor: AppPalette.surface,
  },
  budgetInputError: {
    borderColor: '#EF4444',
  },
  errorText: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: '#EF4444',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 20,
  },
  modalCancelButton: {
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundColor: AppPalette.surfaceSoft,
  },
  modalCancelText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: AppPalette.textMuted,
  },
  modalConfirmButton: {
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: AppPalette.brand,
  },
  modalButtonDisabled: {
    opacity: 0.6,
  },
  modalConfirmText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  });
}

export const styles = createAccountingStyles(PRODUCTIVITY_PALETTE.dark);
