import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  assetSafeArea: {
    backgroundColor: 'transparent',
  },
  screen: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  assetScreen: {
    backgroundColor: 'transparent',
  },
  assetGradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 120,
    gap: 14,
  },
  assetScrollContent: {
    paddingTop: 12,
    paddingBottom: 132,
    gap: 18,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  assetPage: {
    gap: 18,
  },
  assetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  assetHeaderTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  assetHeaderSpacer: {
    width: 36,
    height: 36,
  },
  assetOverviewCard: {
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  assetOverviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  assetOverviewTextGroup: {
    flex: 1,
  },
  assetOverviewTitle: {
    fontSize: 26,
    lineHeight: 34,
    fontWeight: '600',
    color: '#111827',
  },
  assetOverviewAmount: {
    marginTop: 10,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: '#111827',
  },
  assetOverviewActionGroup: {
    gap: 8,
  },
  assetOverviewActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#EFF6FF',
  },
  assetOverviewActionText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: '#2563EB',
  },
  assetBillLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 30,
  },
  assetBillLinkButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#F8FAFC',
  },
  assetBillLinkText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: '#111827',
  },
  assetOverviewDivider: {
    height: StyleSheet.hairlineWidth,
    marginTop: 18,
    marginBottom: 16,
    backgroundColor: '#E5E7EB',
  },
  assetBalanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  assetBalanceLabel: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: '#111827',
  },
  assetBalanceValue: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '700',
  },
  assetBalancePositive: {
    color: '#111827',
  },
  assetBalanceNegative: {
    color: '#DC2626',
  },
  assetMetricCard: {
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 18,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  assetMetricHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 24,
  },
  assetMetricHeaderLabel: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '600',
    color: '#111827',
  },
  assetMetricHeaderValue: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
  },
  assetMetricGrid: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
  },
  assetMetricStat: {
    flex: 1,
    alignItems: 'center',
    borderRadius: 24,
    paddingHorizontal: 10,
    paddingVertical: 18,
    backgroundColor: '#F8FAFC',
  },
  assetMetricStatLabel: {
    fontSize: 15,
    lineHeight: 20,
    color: '#6B7280',
    textAlign: 'center',
  },
  assetMetricStatValue: {
    marginTop: 16,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '700',
    color: '#111827',
  },
  assetMetricStatUnit: {
    marginTop: 10,
    fontSize: 16,
    lineHeight: 22,
    color: '#374151',
  },
  assetSearchCard: {
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 26,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  assetSearchTitle: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
    color: '#111827',
  },
  assetSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 18,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: '#F2F3F5',
  },
  assetSearchInput: {
    flex: 1,
    paddingVertical: 0,
    fontSize: 16,
    lineHeight: 22,
    color: '#111827',
  },
  assetSearchPlaceholder: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    color: '#6B7280',
  },
  assetRangeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  assetRangeChip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#EFF6FF',
  },
  assetRangeChipActive: {
    backgroundColor: '#2563EB',
  },
  assetRangeChipText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#2563EB',
  },
  assetRangeChipTextActive: {
    color: '#FFFFFF',
  },
  assetTrendPanel: {
    marginTop: 20,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 14,
    backgroundColor: '#F8FAFC',
  },
  assetTrendHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  assetTrendName: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#111827',
  },
  assetTrendCode: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: '#6B7280',
  },
  assetTrendPriceGroup: {
    alignItems: 'flex-end',
  },
  assetTrendPrice: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#111827',
  },
  assetTrendRate: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  assetTrendChart: {
    marginTop: 18,
    height: 132,
    overflow: 'hidden',
  },
  assetTrendFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  assetTrendFooterText: {
    fontSize: 12,
    lineHeight: 16,
    color: '#6B7280',
  },
  assetCandleDetailCard: {
    marginTop: 12,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
  },
  assetCandleDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  assetCandleDetailTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: '#111827',
  },
  assetCandleDetailRate: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  assetCandleDetailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 6,
  },
  assetCandleDetailText: {
    width: '50%',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: '#64748B',
  },
  assetTrendEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 24,
    backgroundColor: '#F8FAFC',
    gap: 8,
  },
  assetTrendEmptyText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#64748B',
    textAlign: 'center',
  },
  assetSearchModalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  assetSearchModalCard: {
    width: '100%',
    height: '60%',
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.18,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 14,
  },
  assetSearchModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  assetSearchModalTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '800',
    color: '#111827',
  },
  assetSearchModalClose: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: '#F1F5F9',
  },
  assetSearchModalInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#F2F3F5',
  },
  assetSearchResultList: {
    paddingTop: 14,
    paddingBottom: 8,
    gap: 10,
  },
  assetSearchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: '#F8FAFC',
  },
  assetSearchResultName: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#111827',
  },
  assetSearchResultMeta: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: '#64748B',
  },
  assetSearchResultPrice: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#111827',
  },
  assetSearchEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 42,
    gap: 8,
  },
  assetSearchEmptyText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#64748B',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  monthText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#262626',
  },
  heroCard: {
    height: 192,
    borderRadius: 18,
    overflow: 'hidden',
    justifyContent: 'space-between',
    backgroundColor: '#D4D4D4',
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(38, 38, 38, 0.22)',
  },
  heroContent: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
  },
  heroLabel: {
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '800',
    color: '#E5E7EB',
  },
  heroBalance: {
    marginTop: 4,
    fontSize: 18,
    lineHeight: 28,
    
    color: '#FFFFFF',
  },
  heroTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
  },
  heroTagPressed: {
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
  },
  heroTagDisabled: {
    opacity: 0.6,
  },
  heroTagText: {
    fontSize: 15,
    lineHeight: 18,
    color: '#525252',
  },
  heroSummary: {
    marginTop: 4,
    fontSize: 18,
    lineHeight: 28,
    color: '#FFFFFF',
  },
  heroSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  heroSummaryLink: {
    paddingVertical: 4,
  },
  card: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#262626',
  },
  cardSubtitle: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 20,
    color: '#9CA3AF',
  },
  assetMetricRow: {
    flexDirection: 'row',
    gap: 12,
  },
  assetMetricItem: {
    flex: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 14,
    backgroundColor: '#F8FAFC',
  },
  assetMetricValue: {
    marginTop: 8,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: '#262626',
  },
  budgetEditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#EFF6FF',
  },
  budgetEditText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: '#3B82F6',
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E7F6EF',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#24C17E',
  },
  budgetSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    gap: 12,
  },
  budgetInfoGroup: {
    flex: 1,
    gap: 4,
  },
  budgetDailyLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  budgetHelpButton: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#EFF6FF',
  },
  budgetHelpText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: '#3B82F6',
  },
  mutedText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#9CA3AF',
  },
  chart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    minHeight: 210,
    marginTop: 10,
    paddingHorizontal: 4,
  },
  chartColumn: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  chartValue: {
    fontSize: 12,
    lineHeight: 16,
    color: '#F28B8E',
  },
  chartBarSlot: {
    height: 128,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  chartBar: {
    width: 11,
    borderRadius: 999,
    backgroundColor: '#F05A5A',
  },
  chartBarPlaceholder: {
    width: 11,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'transparent',
  },
  chartLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: '#9CA3AF',
  },
  billCard: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  billHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: '#FCFCFC',
  },
  billDate: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#262626',
  },
  billTotal: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#262626',
  },
  billItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
  },
  billItemPressed: {
    backgroundColor: '#F8FAFC',
  },
  billItemBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E5E7EB',
  },
  billItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  billItemTextGroup: {
    gap: 2,
  },
  billDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F05A5A',
  },
  billDotIncome: {
    backgroundColor: '#24C17E',
  },
  billItemTitle: {
    fontSize: 16,
    lineHeight: 22,
    color: '#262626',
  },
  billItemMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: '#9CA3AF',
  },
  billItemAmount: {
    fontSize: 15,
    lineHeight: 20,
    color: '#F05A5A',
  },
  billItemAmountIncome: {
    color: '#24C17E',
  },
  emptyBillCard: {
    alignItems: 'center',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 28,
    backgroundColor: '#FFFFFF',
    gap: 8,
  },
  emptyBillTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#262626',
  },
  emptyBillText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  bottomBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 28,
    paddingHorizontal: 28,
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
  },
  bottomTab: {
    width: 56,
    alignItems: 'center',
    gap: 4,
  },
  bottomTabLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: '#9CA3AF',
  },
  bottomTabLabelActive: {
    color: '#3B82F6',
  },
  addButton: {
    width: 56,
    height: 56,
    marginTop: -24,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3B82F6',
    shadowColor: '#3B82F6',
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  actionModalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: 'rgba(15, 23, 42, 0.32)',
  },
  actionSheetCard: {
    width: '80%',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 14,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  actionSheetTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '800',
    color: '#262626',
  },
  actionSheetDescription: {
    marginTop: 6,
    marginBottom: 16,
    fontSize: 14,
    lineHeight: 20,
    color: '#737373',
  },
  actionSheetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: '#F8FAFC',
  },
  actionSheetButtonSpaced: {
    marginTop: 10,
  },
  actionSheetButtonText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#2563EB',
  },
  actionSheetDeleteText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#DC2626',
  },
  actionSheetCancelButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    borderRadius: 18,
    paddingVertical: 13,
    backgroundColor: '#F5F5F5',
  },
  actionSheetCancelText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#525252',
  },
  confirmDialogCard: {
    width: '100%',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  confirmDialogTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '800',
    color: '#262626',
  },
  confirmDialogDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: '#737373',
  },
  confirmDialogActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 20,
  },
  confirmDialogCancelButton: {
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundColor: '#F5F5F5',
  },
  confirmDialogCancelText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#525252',
  },
  confirmDialogDeleteButton: {
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#EF4444',
  },
  confirmDialogDeleteText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  modalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  modalCard: {
    width: '100%',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  modalTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '800',
    color: '#262626',
  },
  modalDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: '#737373',
  },
  pickerScopeRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  pickerScopeButton: {
    flex: 1,
    alignItems: 'center',
    borderRadius: 14,
    paddingVertical: 11,
    backgroundColor: '#F5F5F5',
  },
  pickerScopeButtonActive: {
    backgroundColor: '#EFF6FF',
  },
  pickerScopeText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#737373',
  },
  pickerScopeTextActive: {
    color: '#2563EB',
  },
  pickerSectionTitle: {
    marginTop: 18,
    marginBottom: 10,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
    color: '#262626',
  },
  pickerChipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pickerChip: {
    minWidth: 72,
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: '#F8FAFC',
  },
  pickerChipActive: {
    backgroundColor: '#3B82F6',
  },
  pickerChipText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
    color: '#525252',
  },
  pickerChipTextActive: {
    color: '#FFFFFF',
  },
  budgetInput: {
    marginTop: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#D4D4D4',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    lineHeight: 22,
    color: '#262626',
    backgroundColor: '#FAFAFA',
  },
  budgetInputError: {
    borderColor: '#EF4444',
  },
  errorText: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: '#EF4444',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 20,
  },
  heroImageDialogActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 28,
  },
  heroImageDialogRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalCancelButton: {
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundColor: '#F5F5F5',
  },
  modalCancelText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#525252',
  },
  modalConfirmButton: {
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#3B82F6',
  },
  modalButtonDisabled: {
    opacity: 0.6,
  },
  modalConfirmText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
