import { StyleSheet } from 'react-native';



export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  screen: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  errorText: {
    fontSize: 12,
    lineHeight: 16,
    color: '#FF4D4F',
  },
  iconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: '#262626',
  },
  selectorBar: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 6,
  },
  topSelector: {
    flex: 1,
    gap: 8,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
  },
  topSelectorLabel: {
    fontSize: 13,
    lineHeight: 18,
    color: '#737373',
  },
  topSelectorValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  topSelectorValue: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#262626',
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 18,
  },
  card: {
    gap: 18,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: '#FFFFFF',
  },
  summaryCard: {
    gap: 10,
    borderRadius: 16,
    padding: 14,
    backgroundColor: '#F8FAFC',
  },
  summaryLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#737373',
  },
  summaryTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  summaryIconBadge: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 26,
    backgroundColor: '#EFEFEF',
  },
  summaryTextGroup: {
    flex: 1,
    gap: 2,
  },
  summaryTypeTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: '#262626',
  },
  summaryTypeMeta: {
    fontSize: 14,
    lineHeight: 20,
    color: '#737373',
  },
  field: {
    gap: 8,
  },
  fieldLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#262626',
  },
  input: {
    minHeight: 48,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#D4D4D4',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    lineHeight: 22,
    color: '#262626',
    backgroundColor: '#FAFAFA',
  },
  inputWithPicker: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#D4D4D4',
    borderRadius: 12,
    backgroundColor: '#FAFAFA',
  },
  inputWithPickerError: {
    borderColor: '#FF4D4F',
  },
  inputWithPickerText: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    lineHeight: 22,
    color: '#262626',
  },
  inputPickerButton: {
    width: 52,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: '#D4D4D4',
    backgroundColor: '#EFF6FF',
  },
  remarkInput: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  submitButton: {
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#3B82F6',
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  modalRoot: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.12)',
  },
  modalBackdrop: {
    flex: 1,
  },
  topSheet: {
    position: 'absolute',
    top: 86,
    left: 0,
    right: 0,
    maxHeight: '68%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
  },
  topSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  topSheetTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: '#262626',
  },
  closeButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
  },
  datePickerContent: {
    gap: 12,
    paddingBottom: 8,
  },
  datePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  datePickerMonthButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: '#EFF6FF',
  },
  datePickerMonthText: {
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '800',
    color: '#262626',
  },
  weekdayRow: {
    flexDirection: 'row',
  },
  weekdayText: {
    width: `${100 / 7}%`,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: '#737373',
  },
  dateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 8,
  },
  dateGridItem: {
    width: `${100 / 7}%`,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  dateGridItemMuted: {
    opacity: 0.45,
  },
  dateGridItemActive: {
    borderRadius: 12,
    backgroundColor: '#DBEAFE',
  },
  dateGridItemText: {
    fontSize: 15,
    lineHeight: 28,
    fontWeight: '700',
    color: '#262626',
  },
  dateGridItemTextMuted: {
    color: '#737373',
  },
  dateGridItemTextActive: {
    color: '#2563EB',
  },
  clockPickerContent: {
    gap: 12,
    paddingBottom: 8,
  },
  clockNowButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#EFF6FF',
  },
  clockNowButtonText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: '#2563EB',
  },
  clockPickerSectionTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    color: '#525252',
  },
  clockOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clockOption: {
    width: 46,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
  },
  clockOptionActive: {
    backgroundColor: '#DBEAFE',
  },
  clockOptionText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: '#525252',
  },
  clockOptionTextActive: {
    color: '#2563EB',
  },
  clockPickerDoneButton: {
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#3B82F6',
  },
  clockPickerDoneText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  incomeExpenseOptionList: {
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 6,
  },
  incomeExpenseOption: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    paddingVertical: 14,
    backgroundColor: '#F5F5F5',
  },
  incomeExpenseOptionActive: {
    backgroundColor: '#DBEAFE',
  },
  incomeExpenseOptionText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: '#525252',
  },
  incomeExpenseOptionTextActive: {
    color: '#2563EB',
  },
  billTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 18,
    paddingBottom: 10,
  },
  billTypeOption: {
    width: '24%',
    alignItems: 'center',
    gap: 8,
  },
  billTypeOptionActive: {
    transform: [{ scale: 1.01 }],
  },
  billTypeIconCircle: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 36,
    backgroundColor: '#F0F0F0',
  },
  billTypeIconCircleActive: {
    backgroundColor: '#DBEAFE',
  },
  billTypeOptionLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#525252',
  },
  billTypeOptionLabelActive: {
    fontWeight: '700',
    color: '#2563EB',
  },
});
